import { useEffect, useState } from 'react';
import type { CityProgress, GameResult, ProfileId, RoadProgress, SavedState, Stats } from '../types';
import { blankStats } from '../utils/gameLogic';
import { initialRoadProgress } from '../utils/roadLogic';
const KEY='nahia-eider-jokoak-v1';
const fresh = (): SavedState => ({version:4,settings:{language:'eu',sound:false,difficulty:'auto',reducedMotion:false},profiles:{nahia:blankStats(),eider:blankStats(),team:blankStats()}});
const normalizeStats=(value:unknown):Stats=>{const fallback=blankStats();const raw=value&&typeof value==='object'?value as Partial<Stats>:{};const baseRoad=initialRoadProgress();const givenRoad:Partial<RoadProgress>=raw.road&&typeof raw.road==='object'?raw.road:{};return {...fallback,...raw,best:{...fallback.best,...raw.best},recent:Array.isArray(raw.recent)?raw.recent.filter(x=>typeof x==='boolean').slice(-5):[],days:Array.isArray(raw.days)?raw.days.filter(x=>typeof x==='string').slice(-30):[],sessions:Array.isArray(raw.sessions)?raw.sessions.filter(x=>x&&typeof x.game==='string'&&typeof x.date==='string'&&Number.isFinite(x.correct)&&Number.isFinite(x.total)&&Number.isFinite(x.stars)).slice(-20):[],city:{...fallback.city,...(raw.city&&typeof raw.city==='object'?raw.city:{}),placed:Array.isArray(raw.city?.placed)?raw.city.placed.filter(p=>p&&typeof p.id==='string'&&Number.isInteger(p.x)&&Number.isInteger(p.y)).slice(0,16):[],unlocked:Array.isArray(raw.city?.unlocked)?raw.city.unlocked.filter(x=>typeof x==='string'):[]},road:{...baseRoad,...givenRoad,circuitsPlayed:Array.isArray(givenRoad.circuitsPlayed)?givenRoad.circuitsPlayed.filter((c):c is RoadProgress['circuitsPlayed'][number]=>c==='forest'||c==='cloud'||c==='moon'):[],circuitStats:{...baseRoad.circuitStats,...givenRoad.circuitStats}}};};
export const normalizeSavedState = (s: unknown): SavedState => { const safe=fresh();if(!s||typeof s!=='object'||!('profiles' in s)) return safe;const raw=s as {settings?:Partial<SavedState['settings']>;profiles:Partial<Record<ProfileId,unknown>>};return {version:4,settings:{...safe.settings,...raw.settings},profiles:{nahia:normalizeStats(raw.profiles.nahia),eider:normalizeStats(raw.profiles.eider),team:normalizeStats(raw.profiles.team)}}; };
const load = (): SavedState => { try { return normalizeSavedState(JSON.parse(localStorage.getItem(KEY)??'')); } catch { /* recovery uses safe defaults */ } return fresh(); };
export function useProgress() {
 const [data,setData]=useState<SavedState>(load); useEffect(()=>localStorage.setItem(KEY,JSON.stringify(data)),[data]);
 const setSettings=(patch:Partial<SavedState['settings']>)=>setData(d=>({...d,settings:{...d.settings,...patch}}));
 const saveResult=(profile:ProfileId,r:GameResult)=>setData(d=>{const old=d.profiles[profile]; const today=new Date().toISOString().slice(0,10); const next={...old, stars:old.stars+r.stars, played:old.played+1, correct:old.correct+r.correct, attempts:old.attempts+r.total, animals:old.animals+(r.animals??0),potions:old.potions+(r.potions??0),races:old.races+(r.races??0),gardens:old.gardens+(r.gardens??0),cases:old.cases+(r.cases??0),clues:old.clues+(r.clues??0),maxClueStreak:Math.max(old.maxClueStreak,r.maxClueStreak??0),noHelpCases:old.noHelpCases+(r.noHelpCase?1:0),roadStars:old.roadStars+(r.roadStars??0),roadDistance:Math.max(old.roadDistance,r.roadDistance??0),roadRuns:old.roadRuns+(r.roadRuns??0),obstaclesAvoided:old.obstaclesAvoided+(r.obstaclesAvoided??0),cleanRoads:old.cleanRoads+(r.cleanRoad?1:0),teamWins:old.teamWins+(r.teamWin?1:0),maxPotionStreak:Math.max(old.maxPotionStreak,r.maxPotionStreak??0),lastPlayed:today,days:old.days.includes(today)?old.days:[...old.days,today].slice(-30),best:{...old.best,[r.game]:Math.max(old.best[r.game],r.score)},recent:[...old.recent,r.correct/r.total>=.7].slice(-5),sessions:[...old.sessions,{game:r.game,date:today,correct:r.correct,total:r.total,stars:r.stars}].slice(-20)};return {...d,profiles:{...d.profiles,[profile]:next}};});
 const updateCity=(profile:ProfileId,city:CityProgress)=>setData(d=>({...d,profiles:{...d.profiles,[profile]:{...d.profiles[profile],city}}}));
 const updateRoad=(profile:ProfileId,road:RoadProgress)=>setData(d=>({...d,profiles:{...d.profiles,[profile]:{...d.profiles[profile],road}}}));
 const reset=(profile?:ProfileId)=>setData(d=>profile?{...d,profiles:{...d.profiles,[profile]:blankStats()}}:fresh());
 return {data,setSettings,saveResult,updateCity,updateRoad,reset};
}
