import { useState } from 'react';
import type { CityProgress, Difficulty, Language, ProfileId, Stats } from '../types';
import { cityItems, type CityItem } from '../data/content';
import { effectiveLevel, random } from '../utils/gameLogic';
import { tr } from '../data/i18n';
type Mission={prompt:string;options:string[];answer:number;reward:CityItem};
const mission=(lang:Language,level:'seed'|'star',owned:string[]):Mission=>{const eu=lang==='eu';const available=cityItems.filter(x=>!owned.includes(x.id));const reward=random(available.length?available:cityItems);const n=level==='seed'?3:7;const choices=[String(n),String(n+1),String(n+2)];const nature=cityItems.find(x=>x.id==='park')!;const library=cityItems.find(x=>x.id==='library')!;const pick=Math.random();if(pick<.34)return {prompt:eu?`Parkeak ${n+3} lore behar ditu eta ${n} ditu. Zenbat falta dira?`:`El parque necesita ${n+3} flores y ya tiene ${n}. ¿Cuántas faltan?`,options:choices,answer:choices.indexOf('3'),reward};if(pick<.67)return {prompt:eu?'Animaliak jolasteko toki bat behar dute. Zer eraikiko dugu?':'Los animales necesitan un sitio para jugar. ¿Qué construimos?',options:[nature.name[lang],library.name[lang],cityItems[0].name[lang]],answer:0,reward:nature};return {prompt:eu?'Zein lekutan aurkituko ditugu liburuak?':'¿En qué lugar encontraremos libros?',options:[library.name[lang],nature.name[lang],cityItems[3].name[lang]],answer:0,reward:library};};
 export function MagicCity({lang,difficulty,stats,profile,onCityChange,onSessionComplete}:{lang:Language;difficulty:Difficulty;stats:Stats;profile:ProfileId;onCityChange:(city:CityProgress)=>void;onSessionComplete:()=>void}){const t=(k:Parameters<typeof tr>[1])=>tr(lang,k);const level=effectiveLevel(difficulty,stats);const [city,setCity]=useState(stats.city);const [current,setCurrent]=useState<Mission|null>(null);const [reward,setReward]=useState<CityItem|null>(null);const [message,setMessage]=useState('');const [moveMode,setMoveMode]=useState(false);const [moving,setMoving]=useState<number|null>(null);const [confirmClear,setConfirmClear]=useState(false);const save=(next:CityProgress)=>{setCity(next);onCityChange(next);};const start=()=>{setCurrent(mission(lang,level,[...city.unlocked,...city.placed.map(x=>x.id)]));setMessage('');};
 const solve=(good:boolean)=>{if(!good){setMessage(lang==='eu'?'Oso gertu! Pentsatu zertarako den eraikina.':'¡Muy cerca! Piensa para qué sirve el edificio.');return;}setReward(current!.reward);setCurrent(null);setMessage(lang==='eu'?'✨ Eraikuntza berri bat irabazi duzu!':'✨ ¡Has ganado una construcción nueva!');};
 const place=(x:number,y:number)=>{if(moving!==null){const placed=[...city.placed];const origin=placed[moving];const occupied=placed.findIndex(p=>p.x===x&&p.y===y);if(occupied>=0){[placed[moving],placed[occupied]]=[{...origin,x:placed[occupied].x,y:placed[occupied].y},{...placed[occupied],x:origin.x,y:origin.y}];}else placed[moving]={...origin,x,y};save({...city,placed});setMoving(null);return;}if(!reward||city.placed.some(p=>p.x===x&&p.y===y))return;const next={...city,placed:[...city.placed,{id:reward.id,x,y}],unlocked:[...city.unlocked.filter(id=>id!==reward.id),reward.id],missions:city.missions+1,happiness:city.happiness+reward.happiness};save(next);if(next.missions%3===0)onSessionComplete();setReward(null);setMessage(lang==='eu'?'🏗️ Primeran! Zure hiria zoriontsuagoa da.':'🏗️ ¡Genial! Tu ciudad está más feliz.');};
 const empty=Array.from({length:16},(_,i)=>({x:i%4,y:Math.floor(i/4)}));const galleryItems=cityItems.filter(i=>city.unlocked.includes(i.id)&&!city.placed.some(p=>p.id===i.id));return <section className="game-shell city-game"><div className="game-top"><div><span className="eyebrow">🏘️ {t('city')}</span><h2>{lang==='eu'?'Zure hiri atsegina':'Tu ciudad amable'}</h2></div><span className="counter">😊 {city.happiness}</span></div><div className="city-milestones"><span className={city.placed.length>=4?'done':''}>🌱 {lang==='eu'?'Barrio Hazia':'Barrio Semilla'} 4</span><span className={city.placed.length>=8?'done':''}>🌈 {lang==='eu'?'Ostadarraren auzoa':'Barrio Arcoíris'} 8</span><span className={city.placed.length>=12?'done':''}>⭐ {lang==='eu'?'Izar Hiria':'Ciudad Estrella'} 12</span></div><div className="city-toolbar"><button className="secondary" onClick={start} disabled={!!current||!!reward}>{lang==='eu'?'Misio berria':'Nueva misión'} ({city.missions%3}/3)</button><button className={moveMode?'primary':'secondary'} onClick={()=>{setMoveMode(!moveMode);setMoving(null)}}>↔ {t('moveCity')}</button><button className="secondary" onClick={()=>setConfirmClear(true)}>🧹 {t('clearCity')}</button></div>{current&&<div className="city-mission"><h3>📜 {current.prompt}</h3><div className="answers">{current.options.map((o,i)=><button className="answer" key={o} onClick={()=>solve(i===current.answer)}>{o}</button>)}</div></div>}{reward&&<div className="placement-callout"><strong>{reward.icon} {reward.name[lang]}</strong><p>{lang==='eu'?'Aukeratu lursail huts bat kokatzeko.':'Elige una parcela vacía para colocarla.'}</p></div>}<div className="city-grid" aria-label={t('city')}>{empty.map(cell=>{const index=city.placed.findIndex(p=>p.x===cell.x&&p.y===cell.y);const piece=index>=0?cityItems.find(i=>i.id===city.placed[index].id):undefined;return <button key={`${cell.x}-${cell.y}`} className={`city-plot ${piece?'occupied':''} ${moving===index?'moving':''}`} onClick={()=>moveMode&&piece?setMoving(index):place(cell.x,cell.y)} aria-label={piece?piece.name[lang]:(lang==='eu'?'Lursail hutsa':'Parcela vacía')}>{piece?<><span>{piece.icon}</span><small>{piece.name[lang]}</small></>:<span>＋</span>}</button>})}</div><div className="gallery"><h3>🎒 {t('gallery')}</h3><div>{galleryItems.length?galleryItems.map(i=><span key={i.id} title={i.desc[lang]}>{i.icon} {i.name[lang]}</span>):<p>{lang==='eu'?'Misio bat osatu eraikuntzak aurkitzeko.':'Completa una misión para descubrir construcciones.'}</p>}</div></div><p className="good-feedback">{message}</p>{confirmClear&&<div className="inline-confirm"><p>{lang==='eu'?'Ziur zaude hiri honetako eraikin guztiak kentzea nahi duzula?':'¿Quieres quitar todos los edificios de esta ciudad?'}</p><button className="secondary" onClick={()=>setConfirmClear(false)}>{t('cancel')}</button><button className="danger" onClick={()=>{save({placed:[],unlocked:[],missions:0,happiness:0});setConfirmClear(false)}}>{t('delete')}</button></div>}</section>;
}
