import { useEffect, useState } from 'react';
import type { Difficulty, GameResult, Language, ProfileId, Stats } from '../types';
import { calculateStars, detectiveCases, effectiveLevel, generateDetectivePuzzle, validateSequence } from '../utils/gameLogic';
import { tr } from '../data/i18n';

export function MuseumDetectives({lang,difficulty,stats,profile,onComplete}:{lang:Language;difficulty:Difficulty;stats:Stats;profile:ProfileId;onComplete:(r:GameResult)=>void}){
 const level=effectiveLevel(difficulty,stats);const [caseName]=useState(()=>detectiveCases[lang][Math.floor(Math.random()*detectiveCases[lang].length)]);const [puzzles]=useState(()=>Array.from({length:5},()=>generateDetectivePuzzle(level,lang)));const [step,setStep]=useState(-1);const [correct,setCorrect]=useState(0);const [streak,setStreak]=useState(0);const [maxStreak,setMaxStreak]=useState(0);const [help,setHelp]=useState(false);const [hidden,setHidden]=useState(false);const [sequence,setSequence]=useState<string[]>([]);const [message,setMessage]=useState(''); const t=(k:Parameters<typeof tr>[1])=>tr(lang,k);const puzzle=puzzles[Math.max(0,step)];
 useEffect(()=>{if(step>=0&&puzzle?.kind==='memory'){setHidden(false);const id=window.setTimeout(()=>setHidden(true),level==='seed'?3600:2200);return()=>clearTimeout(id);}},[step,puzzle,level]);
 const advance=(good:boolean)=>{if(!good){setMessage(`${t('tryAgain')} ${puzzle.hint}`);setStreak(0);return;}const next=step+1;const newCorrect=correct+1;const newStreak=streak+1;setMessage(t('correct'));window.setTimeout(()=>{if(next===5){onComplete({game:'museum',score:newCorrect,correct:newCorrect,total:5,stars:calculateStars(newCorrect,5),cases:1,clues:5,maxClueStreak:Math.max(maxStreak,newStreak),noHelpCase:!help});}else{setCorrect(newCorrect);setStreak(newStreak);setMaxStreak(Math.max(maxStreak,newStreak));setStep(next);setSequence([]);setMessage('');}},550);};
 const orderClick=(item:string)=>{const expected=[...puzzle.options].sort((a,b)=>Number(a)-Number(b));const next=[...sequence,item];setSequence(next);if(!validateSequence(next,expected)){setSequence([]);advance(false);return;}if(next.length===expected.length)advance(true);};
 if(step===-1)return <section className="game-shell museum-game intro-panel"><span className="museum-big">🏛️</span><p className="eyebrow">🕵️ {t('museum')}</p><h2>{caseName}</h2><p>{lang==='eu'?'Museoan zerbait galdu da! Bildu bost pista objektu magikoa aurkitzeko.':'¡Algo se ha perdido en el museo! Reúne cinco pistas para encontrar el objeto mágico.'}</p><button className="primary" onClick={()=>setStep(0)}>{t('start')} →</button></section>;
 const turn=profile==='team'?(step%2===0?'Nahia':'Eider'):null;return <section className="game-shell museum-game"><div className="game-top"><div><span className="eyebrow">🕵️ {caseName}</span><h2>{lang==='eu'?'Bilatu hurrengo pista':'Busca la siguiente pista'}</h2></div><span className="counter">{step+1} / 5</span></div>{turn&&<p className="turn-pill">{t('turn')}: <strong>{turn}</strong></p>}<div className="museum-room"><span>🖼️</span><span>🏺</span><span>🦴</span><span>🗿</span></div><div className="question-card detective-card"><div className="evidence">{puzzle.display.map((x,i)=><span key={i} className={puzzle.kind==='memory'&&hidden?'hidden-evidence':''}>{x}</span>)}</div><h3>{puzzle.kind==='memory'&&!hidden?(lang==='eu'?'Gogoratu objektuak...':'Recuerda los objetos...'):puzzle.prompt}</h3>{puzzle.kind==='order'?<div className="answers">{puzzle.options.map(o=><button className={`answer ${sequence.includes(o)?'used':''}`} disabled={sequence.includes(o)} key={o} onClick={()=>orderClick(o)}>{o}</button>)}</div>:<div className="answers">{puzzle.options.map((o,i)=><button className="answer" key={`${o}-${i}`} onClick={()=>advance(i===puzzle.answer)} disabled={puzzle.kind==='memory'&&!hidden}>{o}</button>)}</div>}<button className="read-button" onClick={()=>{setHelp(true);setMessage(`💡 ${puzzle.hint}`)}}>💡 {t('hint')}</button>{message&&<p className={message.startsWith(t('tryAgain'))?'gentle-feedback':'good-feedback'}>{message}</p>}</div></section>;
}
