import { useState } from 'react';
import type { Difficulty, GameResult, Language, Stats } from '../types';
import { calculateStars, effectiveLevel } from '../utils/gameLogic';

type Challenge={a:number;b:number;add:boolean};
const makeChallenge=(level:'seed'|'star'):Challenge=>{const add=Math.random()>.38;const max=level==='seed'?10:20;const a=1+Math.floor(Math.random()*(max-1));const b=1+Math.floor(Math.random()*(add?max-a:a));return {a,b,add};};
const label=(lang:Language,eu:string,es:string)=>lang==='eu'?eu:es;
export function NumberGarden({lang,difficulty,stats,onComplete}:{lang:Language;difficulty:Difficulty;stats:Stats;onComplete:(r:GameResult)=>void}){
 const level=effectiveLevel(difficulty,stats);const [challenge,setChallenge]=useState(()=>makeChallenge(level));const [round,setRound]=useState(0);const [picked,setPicked]=useState<number[]>([]);const [firstTry,setFirstTry]=useState(true);const [correct,setCorrect]=useState(0);const [message,setMessage]=useState('');const answer=challenge.add?challenge.a+challenge.b:challenge.a-challenge.b;const flowers=Array.from({length:level==='seed'?10:20},(_,i)=>i);
 const choose=(n:number)=>{const next=[...picked,n];setPicked(next);if(next.length<answer)return;if(next.length>answer){setFirstTry(false);setPicked([]);setMessage(label(lang,'Saiatu berriro: zenbatu loreak lasai.','Prueba otra vez: cuenta las flores con calma.'));return;}const newCorrect=correct+(firstTry?1:0);setMessage(label(lang,'✨ Lorategia loratu da!','✨ ¡El jardín ha florecido!'));window.setTimeout(()=>{if(round===4){onComplete({game:'garden',score:newCorrect,correct:newCorrect,total:5,stars:calculateStars(newCorrect,5),gardens:5});return;}setCorrect(newCorrect);setRound(round+1);setChallenge(makeChallenge(level));setPicked([]);setFirstTry(true);setMessage('');},750);};
 const reset=()=>{setFirstTry(false);setPicked([]);};
 return <section className="game-shell garden-game"><div className="game-top"><div><span className="eyebrow">🌼 {label(lang,'ZENBAKIEN LORATEGIA','JARDÍN DE NÚMEROS')}</span><h2>{label(lang,'Zenbatu, ukitu eta loratu','Cuenta, toca y hazlo florecer')}</h2></div><span className="counter">{round+1} / 5</span></div><div className="garden-sky"><span>☀️</span><span>🦋</span><span>☁️</span></div><div className="garden-question"><strong>{challenge.a} {challenge.add?'＋':'−'} {challenge.b} = ?</strong><p>{label(lang,`Aukeratu ${answer} lore.`,`Elige ${answer} flores.`)}</p></div><div className="flower-bed" aria-label={label(lang,'Loreak zenbatzeko','Flores para contar')}>{flowers.map(n=><button key={n} className={picked.includes(n)?'flower picked':'flower'} onClick={()=>choose(n)} disabled={picked.includes(n)} aria-label={label(lang,`Lorea ${n+1}`,`Flor ${n+1}`)}>{picked.includes(n)?'🌸':'🌱'}</button>)}</div><div className="garden-actions"><span>🌼 {picked.length} / {answer}</span><button className="secondary" onClick={reset}>{label(lang,'Hasi berriro','Empezar de nuevo')}</button></div>{message&&<p className="good-feedback" role="status">{message}</p>}<p className="game-note">{label(lang,'Ukitu loreak banan-banan; akatsak ikasteko pausoak dira.','Toca las flores una a una; los errores son pasos para aprender.')}</p></section>;
}
