import { useEffect, useState } from 'react';
import type { Difficulty, GameResult, Ingredient, Language, ProfileId, Stats } from '../types';
import { ingredients, potionNames } from '../data/content';
import { calculateStars, effectiveLevel, random } from '../utils/gameLogic';
import { tr } from '../data/i18n';
type Recipe={items:Ingredient[];name:string};
const createRecipe=(lang:Language,level:'seed'|'star'):Recipe=>{const bank=ingredients(lang); const length=(level==='seed'?2:4)+Math.floor(Math.random()*(level==='seed'?3:4)); return {items:Array.from({length},()=>random(bank)),name:random(potionNames[lang])};};
export function PotionLab({lang,difficulty,stats,profile,onComplete}:{lang:Language;difficulty:Difficulty;stats:Stats;profile:ProfileId;onComplete:(r:GameResult)=>void}) {
 const level=effectiveLevel(difficulty,stats); const [recipe,setRecipe]=useState(()=>createRecipe(lang,level)); const [round,setRound]=useState(0); const [added,setAdded]=useState<Ingredient[]>([]); const [show,setShow]=useState(true); const [message,setMessage]=useState(''); const [firstTry,setFirstTry]=useState(true); const [correct,setCorrect]=useState(0); const [streak,setStreak]=useState(0); const [maxStreak,setMaxStreak]=useState(0); const [review,setReview]=useState(false);
 useEffect(()=>{const id=window.setTimeout(()=>setShow(false),level==='seed'?4300:2500);return()=>clearTimeout(id);},[recipe,level]);
 const next=()=>{const won=firstTry;const nextRound=round+1;const finalCorrect=correct+(won?1:0);if(nextRound===5){onComplete({game:'potions',score:finalCorrect,correct:finalCorrect,total:5,stars:calculateStars(finalCorrect,5),potions:5,maxPotionStreak:maxStreak});return;}setCorrect(finalCorrect);setStreak(won?streak+1:0);setMaxStreak(Math.max(maxStreak,won?streak+1:streak));setRound(nextRound);setRecipe(createRecipe(lang,level));setAdded([]);setShow(true);setMessage('');setFirstTry(true);};
 const add=(ing:Ingredient)=>{if(show)return; const wanted=recipe.items[added.length]; if(ing.id!==wanted.id){setFirstTry(false);setStreak(0);setMessage(lang==='eu'?'Oso gertu! Begiratu hurrengo osagaia.':'¡Muy cerca! Mira el siguiente ingrediente.');return;}const joined=[...added,ing];setAdded(joined);if(joined.length===recipe.items.length){setMessage(`${lang==='eu'?'✨ Edabea prest!':'✨ ¡Poción lista!'} ${recipe.name}`);window.setTimeout(next,900);}};
 const reveal=()=>{setShow(true);setReview(true);window.setTimeout(()=>setShow(false),2500);}; const turn=profile==='team'?(round%2===0?'Nahia':'Eider'):'';
 return <section className="game-shell potion-game"><div className="game-top"><div><span className="eyebrow">🧪 {tr(lang,'potionName')}</span><h2>{lang==='eu'?'Nahastu magia apur bat':'Mezcla un poquito de magia'}</h2></div><span className="counter">{round+1} / 5</span></div>{turn&&<p className="turn-pill">{tr(lang,'turn')}: <strong>{turn}</strong></p>}<div className="potion-stage"><div className={`cauldron ${added.length?'filled':''}`} style={{'--fill': recipe.items[added.length-1]?.color ?? '#a989e8'} as React.CSSProperties}><span>🫧</span><span>🫧</span><b>{added.map(x=>x.icon).join(' ')||'✨'}</b></div><div className={`recipe-card ${show?'shown':'hidden-recipe'}`}><strong>📜 {tr(lang,'recipe')}: {recipe.name}</strong><div className="recipe-line">{recipe.items.map((x,i)=><span key={i} title={x.name}>{x.icon}</span>)}</div>{!show&&<small>?</small>}</div></div><p className="instruction">{show?(lang==='eu'?'Gogoratu osagaien ordena...':'Recuerda el orden de ingredientes...'):tr(lang,'add')}</p><div className="ingredient-grid">{ingredients(lang).map(ing=><button className="ingredient" style={{borderColor:ing.color}} key={ing.id} onClick={()=>add(ing)} disabled={show}><span>{ing.icon}</span>{ing.name}</button>)}</div><button className="secondary recipe-button" onClick={reveal}>{tr(lang,'seeRecipe')} {review?'(☆)':'(⭐)'}</button>{message&&<p className="good-feedback" role="status">{message}</p>}</section>;
}
