import { useState } from 'react';
import type { Difficulty, GameResult, Language, ProfileId, Stats } from '../types';
import { calculateStars, effectiveLevel, generateQuestion } from '../utils/gameLogic';
import { tr } from '../data/i18n';
export function QuizRace({lang,difficulty,stats,profile,onComplete}:{lang:Language;difficulty:Difficulty;stats:Stats;profile:ProfileId;onComplete:(r:GameResult)=>void}) {
 const [questions]=useState(()=>Array.from({length:10},()=>generateQuestion(effectiveLevel(difficulty,stats),lang,'race')));const [step,setStep]=useState(0);const [correct,setCorrect]=useState(0);const [mine,setMine]=useState(0);const [friend,setFriend]=useState(0);const [feedback,setFeedback]=useState(''); const q=questions[step]; const joint=profile==='team';
 const speak=()=>window.speechSynthesis?.speak(new SpeechSynthesisUtterance(q.prompt));
 function choose(i:number){const good=i===q.answer; if(!good){setFeedback(`${tr(lang,'tryAgain')} ${q.hint??''}`);return;} const boost=Math.random()>.77?2:1;setFeedback(`${tr(lang,'correct')} ${boost===2?'🌈 Turbo!':''}`);window.setTimeout(()=>{const next=step+1;const newCorrect=correct+1; const rival=joint?friend:Math.min(10,friend+(Math.random()>.35?1:0));if(next===10)onComplete({game:'race',score:newCorrect,correct:newCorrect,total:10,stars:calculateStars(newCorrect,10),races:1,teamWin:joint||newCorrect>=6});else{setCorrect(newCorrect);setMine(Math.min(10,mine+boost));setFriend(rival);setStep(next);setFeedback('');}},600);}
 const player=joint?(step%2===0?'Nahia':'Eider'):(lang==='eu'?'Zu':'Tú');
 return <section className="game-shell race-game"><div className="game-top"><div><span className="eyebrow">🏁 {tr(lang,'raceName')}</span><h2>{lang==='eu'?'Helmuga dibertigarria':'Una meta divertida'}</h2></div><span className="counter">{step+1} / 10</span></div><p className="turn-pill">{tr(lang,'turn')}: <strong>{player}</strong></p><div className="track"><div className="lane"><span className="racer" style={{left:`${mine*9}%`}}>🛴</span>{Array.from({length:11},(_,i)=><i key={i}>{i===10?'🏁':i===4||i===8?'🌈':'·'}</i>)}</div><div className="lane rival"><span className="racer" style={{left:`${friend*9}%`}}>{joint?'🚲':'🦊'}</span>{Array.from({length:11},(_,i)=><i key={i}>·</i>)}</div></div><div className="question-card"><h3>{q.prompt}</h3><div className="answers">{q.options.map((o,i)=><button className="answer" key={`${o}${i}`} onClick={()=>choose(i)}>{o}</button>)}</div>{typeof window!=='undefined'&&'speechSynthesis'in window&&<button className="read-button" onClick={speak}>🔊 {tr(lang,'read')}</button>}{feedback&&<p className={feedback.startsWith(tr(lang,'tryAgain'))?'gentle-feedback':'good-feedback'} role="status">{feedback}</p>}</div></section>;
}
