import { useEffect, useState } from 'react';
import type { GameId, GameResult, ProfileId, View } from './types';
import { tr } from './data/i18n';
import { achievementList } from './utils/gameLogic';
import { useProgress } from './hooks/useProgress';
import { AnimalRescue } from './games/AnimalRescue';
import { PotionLab } from './games/PotionLab';
import { QuizRace } from './games/QuizRace';
import { MuseumDetectives } from './games/MuseumDetectives';
import { MagicCity } from './games/MagicCity';
import { StarRoad } from './games/StarRoad';
import { NumberGarden } from './games/NumberGarden';

const profileInfo:Record<ProfileId,{name:string;emoji:string;color:string;desc:{eu:string;es:string}}>={nahia:{name:'Nahia',emoji:'🦋',color:'#ed7b9c',desc:{eu:'Arrosa distiratsua',es:'Rosa brillante'}},eider:{name:'Eider',emoji:'🌼',color:'#6c9df1',desc:{eu:'Urdin alaia',es:'Azul alegre'}},team:{name:'Nahia + Eider',emoji:'🤝',color:'#8c78d8',desc:{eu:'Elkarrekin hobe',es:'Mejor juntas'}}};
const gameInfo:Record<GameId,{icon:string;name:'animalName'|'potionName'|'raceName'|'museum'|'city'|'road'|'garden';desc:'animalDesc'|'potionDesc'|'raceDesc'|'museumDesc'|'cityDesc'|'roadDesc'|'gardenDesc';difficulty:string}>={animals:{icon:'🦊',name:'animalName',desc:'animalDesc',difficulty:'★ ☆ ☆'},potions:{icon:'🧪',name:'potionName',desc:'potionDesc',difficulty:'★ ★ ☆'},race:{icon:'🏁',name:'raceName',desc:'raceDesc',difficulty:'★ ★ ☆'},museum:{icon:'🕵️',name:'museum',desc:'museumDesc',difficulty:'★ ★ ☆'},city:{icon:'🏘️',name:'city',desc:'cityDesc',difficulty:'★ ☆ ☆'},road:{icon:'🚙',name:'road',desc:'roadDesc',difficulty:'★ ★ ☆'},garden:{icon:'🌼',name:'garden',desc:'gardenDesc',difficulty:'★ ☆ ☆'}};
function Modal({children,onClose}:{children:React.ReactNode;onClose?:()=>void}){return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.();}}><div className="modal" role="dialog" aria-modal="true">{children}</div></div>}

export default function App(){
 const {data,setSettings,saveResult,updateCity,updateRoad,reset}=useProgress();const {language:lang,sound,difficulty,reducedMotion}=data.settings;const [view,setView]=useState<View>('welcome');const [profile,setProfile]=useState<ProfileId>('nahia');const [game,setGame]=useState<GameId>('animals');const [loading,setLoading]=useState(true);const [modal,setModal]=useState<'help'|'leave'|'reset'|null>(null);const [resetTarget,setResetTarget]=useState<ProfileId|'all'|null>(null);const [result,setResult]=useState<GameResult|null>(null);
 useEffect(()=>{const id=window.setTimeout(()=>setLoading(false),1050);return()=>clearTimeout(id);},[]);useEffect(()=>{document.documentElement.lang=lang;},[lang]);useEffect(()=>{document.body.classList.toggle('reduce-motion',reducedMotion);},[reducedMotion]);
 const t=(key:Parameters<typeof tr>[1])=>tr(lang,key); const profileStats=data.profiles[profile];
 const beep=(good=true)=>{if(!sound)return;try{const ctx=new AudioContext();const o=ctx.createOscillator();const g=ctx.createGain();o.frequency.value=good?660:330;g.gain.setValueAtTime(.06,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.13);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.14);}catch{/* sound is optional */}};
 const complete=(r:GameResult)=>{beep(true);saveResult(profile,r);setResult(r);};
 const leave=()=>{if(view==='game')setModal('leave');else setView(view==='menu'?'welcome':'menu');};
 if(loading)return <main className="loading-screen"><div className="loading-cloud">☁️</div><h1>Nahia eta Eiderren Jokoak</h1><p>{t('tagline')}</p><div className="sparkles">✦ ✧ ✦</div></main>;
 return <main className="app-shell"><header className="topbar"><button className="brand" onClick={()=>setView(profile?'menu':'welcome')} aria-label="Nahia eta Eiderren Jokoak">🌈 <span>Nahia eta Eiderren <b>Jokoak</b></span></button><div className="header-actions"><div className="lang-toggle" aria-label={t('language')}><button className={lang==='eu'?'active':''} onClick={()=>setSettings({language:'eu'})}>EU</button><button className={lang==='es'?'active':''} onClick={()=>setSettings({language:'es'})}>ES</button></div><button className="round-button" onClick={()=>setSettings({sound:!sound})} aria-label={t('sound')}>{sound?'🔊':'🔇'}</button><button className="round-button" onClick={()=>setView('settings')} aria-label={t('settings')}>⚙️</button><button className="round-button" onClick={()=>setModal('help')} aria-label={t('help')}>?</button></div></header>
 {view==='welcome'&&<Welcome lang={lang} data={data} choose={p=>{setProfile(p);setView('menu');}} />}
 {view==='menu'&&<Menu lang={lang} profile={profile} data={data} chooseGame={g=>{setGame(g);setView('game');}} goProgress={()=>setView('progress')} />}
 {view==='game'&&<><button className="back-link" onClick={leave}>← {t('back')}</button>{game==='animals'&&<AnimalRescue lang={lang} difficulty={difficulty} stats={profileStats} onComplete={complete}/>} {game==='potions'&&<PotionLab lang={lang} difficulty={difficulty} stats={profileStats} profile={profile} onComplete={complete}/>} {game==='race'&&<QuizRace lang={lang} difficulty={difficulty} stats={profileStats} profile={profile} onComplete={complete}/>} {game==='museum'&&<MuseumDetectives lang={lang} difficulty={difficulty} stats={profileStats} profile={profile} onComplete={complete}/>} {game==='garden'&&<NumberGarden lang={lang} difficulty={difficulty} stats={profileStats} onComplete={complete}/>} {game==='city'&&<MagicCity lang={lang} difficulty={difficulty} stats={profileStats} profile={profile} onCityChange={city=>updateCity(profile,city)} onSessionComplete={()=>complete({game:'city',score:profileStats.city.happiness,correct:3,total:3,stars:3,teamWin:profile==='team'})}/>} {game==='road'&&<StarRoad lang={lang} difficulty={difficulty} stats={profileStats} profile={profile} reducedMotion={reducedMotion} onRoadUpdate={road=>updateRoad(profile,road)} onComplete={complete}/>}</>}
 {view==='progress'&&<Progress lang={lang} data={data} profile={profile} />}
 {view==='settings'&&<Settings lang={lang} data={data} setSettings={setSettings} requestReset={target=>{setResetTarget(target);setModal('reset');}} />}
 {modal==='help'&&<Modal onClose={()=>setModal(null)}><span className="modal-icon">💡</span><h2>{t('help')}</h2><p>{t('helpful')}</p><p>{lang==='eu'?'Aukeratu profila, joko bat eta hasi. Izarrak eta dominak automatikoki gordetzen dira ordenagailu honetan.':'Elige un perfil, un juego y empieza. Las estrellas y medallas se guardan automáticamente en este ordenador.'}</p><button className="primary" onClick={()=>setModal(null)}>{t('close')}</button></Modal>}
 {modal==='leave'&&<Modal><span className="modal-icon">🌷</span><h2>{t('leave')}</h2><p>{lang==='eu'?'Zure aurrerapena ez da gordeko partida honetan.':'El avance de esta partida no se guardará.'}</p><div className="modal-actions"><button className="secondary" onClick={()=>setModal(null)}>{t('continue')}</button><button className="primary" onClick={()=>{setModal(null);setView('menu')}}>{t('exit')}</button></div></Modal>}
 {modal==='reset'&&<Modal><span className="modal-icon">🧹</span><h2>{t('confirm')}</h2><p>{resetTarget==='all'?(lang==='eu'?'Aurrerapen guztiak ezabatuko dira ordenagailu honetan.':'Se borrará todo el progreso de este ordenador.'):(lang==='eu'?`${profileInfo[resetTarget!].name}ren izarrak, partidak eta dominak ezabatuko dira.`:`Se borrarán las estrellas, partidas y medallas de ${profileInfo[resetTarget!].name}.`)}</p><div className="modal-actions"><button className="secondary" onClick={()=>setModal(null)}>{t('cancel')}</button><button className="danger" onClick={()=>{reset(resetTarget==='all'?undefined:resetTarget!);setModal(null)}}>{t('delete')}</button></div></Modal>}
 {result&&<Modal><span className="modal-icon">🎉</span><h2>{t('result')}</h2><div className="result-stars">{'⭐'.repeat(result.stars)}</div><p>{result.correct} / {result.total} · {result.stars} {t('stars')}</p><p>{result.game==='animals'?`${result.animals} ${t('rescued').toLowerCase()}`:result.game==='potions'?`${result.potions} ${t('created').toLowerCase()}`:result.game==='museum'?`${result.clues} ${t('clues').toLowerCase()}`:result.game==='road'?`⭐ ${result.roadStars} · ${t('distance')}: ${result.roadDistance}`:result.game==='city'?`🏘️ ${t('cityMissions')}`:t('raceDone')}</p><div className="modal-actions"><button className="secondary" onClick={()=>{setResult(null);setView('progress')}}>{t('achievements')}</button><button className="primary" onClick={()=>{setResult(null);setView('menu')}}>{t('menu')}</button></div></Modal>}
 </main>;
}
function Welcome({lang,data,choose}:{lang:'eu'|'es';data:ReturnType<typeof useProgress>['data'];choose:(p:ProfileId)=>void}){const t=(k:Parameters<typeof tr>[1])=>tr(lang,k);return <section className="welcome page"><div className="hero"><div className="hero-bubbles">☀️ ☁️ 🦋</div><h1>{t('choose')}</h1><p>{t('tagline')}</p></div><div className="profiles">{(['nahia','eider','team'] as ProfileId[]).map(p=>{const info=profileInfo[p],s=data.profiles[p];return <article className={`profile-card ${p}`} key={p} style={{'--profile-color':info.color} as React.CSSProperties}><div className="avatar">{info.emoji}</div><h2>{p==='team'?t('together'):info.name}</h2><p>{p==='team'?t('togetherSub'):info.desc[lang]}</p><div className="profile-meta"><span>⭐ {s.stars}</span><span>🌱 {s.recent.filter(Boolean).length>=4?t('star'):t('seed')}</span></div><button className="primary" onClick={()=>choose(p)}>{t('enter')} →</button></article>})}</div></section>}
 function Menu({lang,profile,data,chooseGame,goProgress}:{lang:'eu'|'es';profile:ProfileId;data:ReturnType<typeof useProgress>['data'];chooseGame:(g:GameId)=>void;goProgress:()=>void}){const t=(k:Parameters<typeof tr>[1])=>tr(lang,k);const p=profileInfo[profile];return <section className="page menu-page"><div className="menu-heading"><div><p className="eyebrow">{p.emoji} {p.name}</p><h1>{t('games')}</h1><p>{lang==='eu'?'Aukeratu zure hurrengo abentura!':'¡Elige tu próxima aventura!'}</p></div><button className="progress-link" onClick={goProgress}>🏆 {t('achievements')}<span>⭐ {data.profiles[profile].stars}</span></button></div><div className="games-grid">{(Object.keys(gameInfo) as GameId[]).map(id=>{const g=gameInfo[id];return <article className={`game-card ${id}`} key={id}><div className="game-icon">{g.icon}</div><div><h2>{t(g.name)}</h2><p>{t(g.desc)}</p><span className="difficulty">{g.difficulty}</span></div><div className="game-footer"><small>{t('best')}: ⭐ {data.profiles[profile].best[id]}</small><button className="primary" onClick={()=>chooseGame(id)}>{t('play')} →</button></div></article>})}</div></section>}
function Progress({lang,data,profile}:{lang:'eu'|'es';data:ReturnType<typeof useProgress>['data'];profile:ProfileId}){const t=(k:Parameters<typeof tr>[1])=>tr(lang,k);const s=data.profiles[profile];const medals=achievementList(s,data.profiles.team,lang);return <section className="page progress-page"><div className="menu-heading"><div><p className="eyebrow">🏆 {profileInfo[profile].name}</p><h1>{t('achievements')}</h1><p>{lang==='eu'?'Amaitutako jarduera bakoitzak hazia ematen du; praktikak izar bihurtzen du.':'Cada actividad terminada da una semilla; la práctica la convierte en estrella.'}</p></div></div><div className="stat-grid"><Stat icon="⭐" label={t('totalStars')} value={s.stars}/><Stat icon="🎮" label={t('played')} value={s.played}/><Stat icon="📅" label={t('days')} value={s.days.length}/><Stat icon="🦊" label={t('rescued')} value={s.animals}/><Stat icon="🕵️" label={t('clues')} value={s.clues}/><Stat icon="🏘️" label={t('happiness')} value={s.city.happiness}/><Stat icon="🚙" label={t('distance')} value={s.roadDistance}/></div><h2 className="section-title">🗓️ {lang==='eu'?'Azken abenturak':'Últimas aventuras'}</h2><div className="session-list">{s.sessions.length?s.sessions.slice().reverse().slice(0,6).map((x,i)=><div key={`${x.date}-${i}`}><span>{gameInfo[x.game]?.icon}</span><strong>{gameInfo[x.game]?t(gameInfo[x.game].name):x.game}</strong><small>{x.date} · {'⭐'.repeat(x.stars)}</small></div>):<p>{lang==='eu'?'Amaitu lehen jokoa hemen ikusteko.':'Termina un primer juego para verlo aquí.'}</p>}</div><h2 className="section-title">🏅 {t('medals')}</h2><div className="medal-grid">{medals.map(m=><article className={`medal ${m.done?'unlocked':''}`} key={m.name}><span>{m.icon}</span><div><h3>{m.name}</h3><p>{m.desc}</p><div className="meter"><i style={{width:`${Math.min(100,m.current/m.target*100)}%`}}/></div><small>{Math.min(m.current,m.target)} / {m.target} {m.done?'✓':''}</small></div></article>)}</div></section>}
function Stat({icon,label,value}:{icon:string;label:string;value:number}){return <article className="stat"><span>{icon}</span><strong>{value}</strong><small>{label}</small></article>}
function Settings({lang,data,setSettings,requestReset}:{lang:'eu'|'es';data:ReturnType<typeof useProgress>['data'];setSettings:ReturnType<typeof useProgress>['setSettings'];requestReset:(p:ProfileId|'all')=>void}){const t=(k:Parameters<typeof tr>[1])=>tr(lang,k);return <section className="page settings-page"><p className="eyebrow">⚙️</p><h1>{t('settings')}</h1><div className="settings-card"><Setting label={t('language')}><div className="choice-row"><button onClick={()=>setSettings({language:'eu'})} className={data.settings.language==='eu'?'selected':''}>Euskera</button><button onClick={()=>setSettings({language:'es'})} className={data.settings.language==='es'?'selected':''}>Castellano</button></div></Setting><Setting label={t('sound')}><Toggle on={data.settings.sound} label={data.settings.sound?t('on'):t('off')} click={()=>setSettings({sound:!data.settings.sound})}/></Setting><Setting label={t('difficulty')}><div className="choice-row">{(['auto','seed','star'] as const).map(d=><button key={d} className={data.settings.difficulty===d?'selected':''} onClick={()=>setSettings({difficulty:d})}>{d==='auto'?t('automatic'):d==='seed'?t('seed'):t('star')}</button>)}</div></Setting><Setting label={t('reduceMotion')}><Toggle on={data.settings.reducedMotion} label={data.settings.reducedMotion?t('on'):t('off')} click={()=>setSettings({reducedMotion:!data.settings.reducedMotion})}/></Setting></div><div className="reset-card"><h2>🧹 {t('reset')}</h2>{(['nahia','eider','team'] as ProfileId[]).map(p=><button className="secondary" onClick={()=>requestReset(p)} key={p}>{t('resetProfile')}: {profileInfo[p].name}</button>)}<button className="danger outline" onClick={()=>requestReset('all')}>{t('resetAll')}</button></div></section>}
function Setting({label,children}:{label:string;children:React.ReactNode}){return <div className="setting"><strong>{label}</strong>{children}</div>};function Toggle({on,label,click}:{on:boolean;label:string;click:()=>void}){return <button onClick={click} className={`toggle ${on?'on':''}`} aria-pressed={on}><i/>{label}</button>}
